FROM debian:latest AS elxr-container
RUN apt update
RUN apt install -y \ 
    git \
    python3-guestfs \
    libguestfs-tools \
    libguestfs-dev \
    vim \
    pipenv \
    curl wget net-tools \
    pipenv \
    python-is-python3
RUN apt install -y python3-poetry





